# Generated by Django 5.0.1 on 2026-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
            ],
            options={
                'verbose_name': 'Код верификации',
                'verbose_name_plural': 'Коды верификации',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель')], default='student', max_length=10, verbose_name='Роль'),
        ),
    ]
