# Generated by Django 5.0.1 on 2026-01-23 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
