# Generated by Django 5.0.1 on 2026-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Неудачные попытки входа'),
        ),
    ]
