# Generated by Django 5.2.4 on 2026-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_question_course_certificate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_name',
            field=models.CharField(blank=True, help_text='Используется когда учитель выбирает "Другое" и пишет свою категорию', max_length=200, null=True, verbose_name='Название категории (кастомное)'),
        ),
    ]
